FROM debian:trixie-slim

RUN apt-get update && apt-get install curl sudo passwd -y

RUN useradd -u 1000 -m -s /bin/bash dev
RUN echo "dev:123" | chpasswd
RUN usermod -aG sudo dev
RUN mkdir -p /home/dev/bin
RUN chown dev:dev /home/dev/bin

RUN curl -L -o /usr/local/bin/ttyd https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64
RUN chmod +x /usr/local/bin/ttyd

RUN echo '#!/bin/bash' > /usr/local/bin/entrypoint.sh && \
    echo 'set -e' >> /usr/local/bin/entrypoint.sh && \
    echo 'curl -L -o /home/dev/bin/custom-setup "https://raw.githubusercontent.com/carrierpigeondev/argos-remote/refs/heads/main/custom-setup.sh"' >> /usr/local/bin/entrypoint.sh && \
    echo 'chmod +x /home/dev/bin/custom-setup' >> /usr/local/bin/entrypoint.sh && \
    echo 'exec ttyd -i 0.0.0.0 -u 1000 -t fontSize=32 -W bash' >> /usr/local/bin/entrypoint.sh && \
    echo 'set -a; source /etc/environment; set +a;' >> /usr/local/bin/entrypoint.sh && \
    chmod +x /usr/local/bin/entrypoint.sh

RUN echo 'export PATH=/home/dev/bin:$PATH' >> /etc/environment

EXPOSE 7681
USER dev
CMD ["/usr/local/bin/entrypoint.sh"]